/**
 * Master Level — "Eastlight Town"
 *
 * A 400×400 m district generated by the Level Wizard. It includes:
 *  - sculpted heightmap terrain (rolling hills)
 *  - paved central plaza + asphalt roads
 *  - ~30 textured polygon buildings of varied heights
 *  - a glass-and-stone train station with platform, columns, roof, benches
 *  - a 3-car train (locomotive + 2 wagons) with sliding doors
 *  - a closed-loop track encoded as a `ScenePath` (driven by TrainRuntime)
 *  - 4 NPC characters (idle / wave / dance) + 1 playable spawn
 *  - park area with trees and lawn
 *
 * The TrainRuntime in `src/components/level/train/TrainRuntime.tsx` reads
 * `scene.trainSystem` (set here) to move the train, hold at the station,
 * open the doors, accept boarders, and accept cabin possession.
 */

import {
  AnimationKeyframe,
  AnimationTrack,
  CharacterObject,
  DEFAULT_CHARACTER_URL,
  DEFAULT_LAYER_ID,
  EMPTY_SCENE,
  LevelScene,
  PolygonObject,
  PrimitiveObject,
  RGBA,
  SceneLayer,
  SceneLight,
  SceneObject,
  ScenePath,
  TrainSystemConfig,
  Vec3,
  defaultLayers,
  defaultTerrain,
  newId,
} from "../levelTypes";
import {
  TEX_ASPHALT,
  TEX_BRICK,
  TEX_CONCRETE,
  TEX_GLASS_FACADE,
  TEX_GRASS,
  TEX_METAL,
  TEX_PAVERS,
  TEX_STONE,
  TEX_WOOD,
} from "./textureLibrary";

/* ---------- helpers ---------- */

const LAYERS = {
  terrain: "layer_terrain",
  roads: "layer_roads",
  buildings: "layer_buildings",
  station: "layer_station",
  train: "layer_train",
  park: "layer_park",
  characters: "layer_characters",
} as const;

function makeLayers(): SceneLayer[] {
  // First entry must be the Default layer so the existing default-layer logic
  // keeps working. All other layers start collapsed (the Layers panel already
  // defaults `collapsed ?? true` to collapsed, but we set it explicitly).
  return [
    { id: DEFAULT_LAYER_ID, name: "Default", color: "#64748b", visible: true, collapsed: true },
    { id: LAYERS.terrain, name: "Terrain", color: "#3d7a2c", visible: true, collapsed: true },
    { id: LAYERS.roads, name: "Roads & Plaza", color: "#3a3a3a", visible: true, collapsed: true },
    { id: LAYERS.buildings, name: "Buildings", color: "#a4452f", visible: true, collapsed: true },
    { id: LAYERS.station, name: "Train Station", color: "#6ea8c8", visible: true, collapsed: true },
    { id: LAYERS.train, name: "Train", color: "#b8c0c8", visible: true, collapsed: true },
    { id: LAYERS.park, name: "Park", color: "#52a058", visible: true, collapsed: true },
    { id: LAYERS.characters, name: "Characters", color: "#e2a23d", visible: true, collapsed: true },
  ];
}

const C = {
  asphalt: [0.18, 0.18, 0.2, 1] as RGBA,
  paver: [0.55, 0.5, 0.45, 1] as RGBA,
  concrete: [0.5, 0.5, 0.52, 1] as RGBA,
  brick: [0.65, 0.32, 0.22, 1] as RGBA,
  stone: [0.78, 0.7, 0.55, 1] as RGBA,
  glass: [0.4, 0.6, 0.75, 1] as RGBA,
  wood: [0.42, 0.25, 0.13, 1] as RGBA,
  metal: [0.55, 0.58, 0.62, 1] as RGBA,
  grass: [0.24, 0.48, 0.18, 1] as RGBA,
  black: [0.06, 0.06, 0.08, 1] as RGBA,
  white: [0.95, 0.95, 0.96, 1] as RGBA,
  trainRed: [0.7, 0.18, 0.18, 1] as RGBA,
  trainGold: [0.88, 0.7, 0.2, 1] as RGBA,
};

function prim(opts: {
  name: string;
  pos: Vec3;
  size: Vec3;
  rot?: Vec3;
  color?: RGBA;
  shape?: PrimitiveObject["shape"];
  metalness?: number;
  roughness?: number;
  layer?: string;
  textureUrl?: string;
  textureRepeat?: [number, number];
  trainRole?: PrimitiveObject["trainRole"];
  doorOpenOffset?: Vec3;
  id?: string;
}): PrimitiveObject {
  const id = opts.id ?? newId("obj");
  const obj: PrimitiveObject = {
    id,
    name: opts.name,
    kind: "primitive",
    shape: opts.shape ?? "box",
    position: opts.pos,
    rotation: opts.rot ?? [0, 0, 0],
    scale: opts.size,
    visible: true,
    color: opts.color ?? C.concrete,
    metalness: opts.metalness ?? 0.05,
    roughness: opts.roughness ?? 0.85,
    layerId: opts.layer ?? DEFAULT_LAYER_ID,
    trainRole: opts.trainRole,
    doorOpenOffset: opts.doorOpenOffset,
  };
  if (opts.textureUrl) {
    // Apply the texture to every face via the "all" key (works for box-like
    // primitives in PrimitiveMesh) and the per-face keys for boxes.
    const fo: any = {
      all: { textureUrl: opts.textureUrl, repeat: opts.textureRepeat ?? [1, 1] },
    };
    for (const k of ["px", "nx", "py", "ny", "pz", "nz", "side", "top", "bottom"]) {
      fo[k] = { textureUrl: opts.textureUrl, repeat: opts.textureRepeat ?? [1, 1] };
    }
    obj.faceOverrides = fo;
  }
  return obj;
}

function building(opts: {
  name: string;
  cx: number; cz: number;
  w: number; d: number; h: number;
  facade: "brick" | "glass" | "stone" | "concrete" | "wood";
  layer?: string;
}): PrimitiveObject[] {
  const out: PrimitiveObject[] = [];
  const tex = {
    brick: { url: TEX_BRICK, color: C.brick, rep: [Math.max(1, opts.w / 4), Math.max(1, opts.h / 4)] as [number, number] },
    glass: { url: TEX_GLASS_FACADE, color: C.glass, rep: [Math.max(1, opts.w / 6), Math.max(1, opts.h / 4)] as [number, number] },
    stone: { url: TEX_STONE, color: C.stone, rep: [Math.max(1, opts.w / 8), Math.max(1, opts.h / 6)] as [number, number] },
    concrete: { url: TEX_CONCRETE, color: C.concrete, rep: [Math.max(1, opts.w / 6), Math.max(1, opts.h / 6)] as [number, number] },
    wood: { url: TEX_WOOD, color: C.wood, rep: [Math.max(1, opts.w / 3), Math.max(1, opts.h / 6)] as [number, number] },
  }[opts.facade];
  // body
  out.push(prim({
    name: opts.name,
    pos: [opts.cx, opts.h / 2, opts.cz],
    size: [opts.w, opts.h, opts.d],
    color: tex.color,
    metalness: opts.facade === "glass" ? 0.4 : 0.05,
    roughness: opts.facade === "glass" ? 0.25 : 0.85,
    layer: opts.layer ?? LAYERS.buildings,
    textureUrl: tex.url,
    textureRepeat: tex.rep,
  }));
  // flat roof cap
  out.push(prim({
    name: `${opts.name} roof`,
    pos: [opts.cx, opts.h + 0.2, opts.cz],
    size: [opts.w + 0.4, 0.4, opts.d + 0.4],
    color: C.concrete,
    layer: opts.layer ?? LAYERS.buildings,
    textureUrl: TEX_CONCRETE,
    textureRepeat: [Math.max(1, opts.w / 4), Math.max(1, opts.d / 4)],
  }));
  return out;
}

/* ---------- terrain heightmap ---------- */

/** Build a (res+1)×(res+1) heightmap of rolling hills, in metres. */
function buildHeightmap(res: number, sizeXZ: number): number[] {
  const data: number[] = [];
  const k = sizeXZ / res;
  for (let j = 0; j <= res; j++) {
    for (let i = 0; i <= res; i++) {
      const x = (i - res / 2) * k;
      const z = (j - res / 2) * k;
      // Composite of 3 sinusoidal hills + a flat plateau around the centre
      // (where the town + station live).
      const distToCentre = Math.hypot(x, z);
      const plateau = Math.max(0, 1 - distToCentre / 90); // 0..1 weight near centre
      const hill =
        2.5 * Math.sin(x * 0.013) * Math.cos(z * 0.011) +
        1.4 * Math.sin(x * 0.027 + 1.3) * Math.cos(z * 0.019 + 0.4) +
        0.6 * Math.sin(x * 0.05 + 2.1) * Math.cos(z * 0.043 + 1.7);
      // Ridge far from centre (rim of hills)
      const ridge = Math.max(0, (distToCentre - 140) / 60) * 4.0;
      const h = hill * (1 - plateau) + ridge;
      data.push(h);
    }
  }
  return data;
}

/* ---------- track ---------- */

/**
 * Closed oval loop around the town, with a long straight section running
 * along the +X face of the station so the platform is parallel to the rails.
 */
function buildTrack(): ScenePath {
  const pts: Vec3[] = [];
  // Station straight (negative X, parallel to Z axis): x = -28
  // Loop centre is roughly (10, 0, 0). Track major radius ~150.
  const STATION_X = -22;
  const Y = 0.4;
  // Walk the loop in 24 points.
  // Section 1: long straight in front of platform, z from -35 → +35
  pts.push([STATION_X, Y, -35]);
  pts.push([STATION_X, Y, -10]);
  pts.push([STATION_X, Y, 0]); // <- approx station stop point
  pts.push([STATION_X, Y, 15]);
  pts.push([STATION_X, Y, 35]);
  // Section 2: arc to the east, sweeping +X
  for (let i = 1; i <= 8; i++) {
    const a = Math.PI * (1 - i / 8); // from PI (= -X) sweeping down to 0 (= +X)
    const r = 80;
    pts.push([STATION_X + 60 + Math.cos(a) * r, Y, 35 + Math.sin(a) * r * 0.7]);
  }
  // Section 3: straight back along the south rim
  pts.push([130, Y, -40]);
  pts.push([90, Y, -55]);
  pts.push([40, Y, -65]);
  pts.push([-10, Y, -65]);
  // Section 4: arc back to the station straight
  for (let i = 1; i <= 6; i++) {
    const a = Math.PI * (1 + i / 6); // from PI down/around
    const r = 30;
    pts.push([-22 + Math.cos(a) * r, Y, -55 + Math.sin(a) * r]);
  }
  return {
    id: "path_train_track",
    name: "Train Track",
    waypoints: pts,
    color: "#b8c0c8",
    closed: true,
  };
}

/* ---------- main builder ---------- */

export function buildMasterLevelScene(): LevelScene {
  const objects: SceneObject[] = [];
  const animations: AnimationTrack[] = [];

  /* ---- pavers central plaza ---- */
  objects.push(prim({
    name: "Plaza pavers",
    pos: [0, 0.02, 0],
    size: [40, 0.05, 30],
    color: C.paver,
    textureUrl: TEX_PAVERS,
    textureRepeat: [10, 8],
    layer: LAYERS.roads,
  }));

  /* ---- asphalt main road (N–S) ---- */
  objects.push(prim({
    name: "Main road",
    pos: [25, 0.025, 0],
    size: [10, 0.05, 200],
    color: C.asphalt,
    textureUrl: TEX_ASPHALT,
    textureRepeat: [4, 60],
    layer: LAYERS.roads,
  }));
  // dashed white centre-line (a few short bars)
  for (let z = -90; z <= 90; z += 6) {
    objects.push(prim({
      name: `Lane mark ${z}`,
      pos: [25, 0.055, z],
      size: [0.2, 0.01, 2.5],
      color: C.white,
      layer: LAYERS.roads,
      metalness: 0,
      roughness: 0.9,
    }));
  }

  /* ---- east-west cross road ---- */
  objects.push(prim({
    name: "Cross road",
    pos: [0, 0.025, 35],
    size: [200, 0.05, 8],
    color: C.asphalt,
    textureUrl: TEX_ASPHALT,
    textureRepeat: [60, 4],
    layer: LAYERS.roads,
  }));

  /* ---- buildings ---- */
  const buildingSpecs: Array<{ x: number; z: number; w: number; d: number; h: number; facade: any; name: string }> = [
    // East commercial strip
    { x: 45, z: 60, w: 14, d: 14, h: 24, facade: "glass", name: "Aurora Tower" },
    { x: 65, z: 55, w: 16, d: 14, h: 18, facade: "concrete", name: "Lumen Office" },
    { x: 45, z: 80, w: 12, d: 12, h: 14, facade: "brick", name: "Brick & Co." },
    { x: 65, z: 80, w: 12, d: 12, h: 9, facade: "stone", name: "Stone Hall" },
    { x: 45, z: 100, w: 18, d: 14, h: 30, facade: "glass", name: "Skyline Plaza" },
    { x: 70, z: 100, w: 14, d: 16, h: 22, facade: "brick", name: "Eastlight Lofts" },
    // East residential
    { x: 50, z: 130, w: 10, d: 10, h: 7, facade: "wood", name: "Cottage A" },
    { x: 64, z: 130, w: 10, d: 10, h: 7, facade: "wood", name: "Cottage B" },
    { x: 78, z: 130, w: 10, d: 10, h: 7, facade: "wood", name: "Cottage C" },
    { x: 50, z: 145, w: 10, d: 10, h: 7, facade: "wood", name: "Cottage D" },
    { x: 64, z: 145, w: 10, d: 10, h: 7, facade: "wood", name: "Cottage E" },
    // South commercial
    { x: 60, z: -30, w: 14, d: 18, h: 12, facade: "brick", name: "Market Hall" },
    { x: 80, z: -30, w: 14, d: 18, h: 16, facade: "stone", name: "Civic Library" },
    { x: 60, z: -55, w: 18, d: 12, h: 20, facade: "glass", name: "Crystal Bank" },
    { x: 85, z: -55, w: 16, d: 16, h: 14, facade: "concrete", name: "City Works" },
    // North district
    { x: 50, z: 175, w: 20, d: 16, h: 26, facade: "glass", name: "Heliotrope" },
    { x: 80, z: 175, w: 14, d: 14, h: 12, facade: "brick", name: "North Forge" },
    // West (behind station rails)
    { x: -60, z: -20, w: 14, d: 14, h: 18, facade: "brick", name: "West Mill" },
    { x: -60, z: 10, w: 12, d: 12, h: 9, facade: "stone", name: "Old Post" },
    { x: -60, z: 35, w: 16, d: 12, h: 22, facade: "concrete", name: "Granary" },
    { x: -85, z: 0, w: 14, d: 18, h: 14, facade: "wood", name: "Workshop" },
    // Tall feature towers
    { x: 110, z: 20, w: 20, d: 20, h: 60, facade: "glass", name: "Eastlight Spire" },
    { x: 0, z: -80, w: 16, d: 16, h: 36, facade: "concrete", name: "Bell Tower" },
    // Industrial cluster
    { x: 130, z: -30, w: 30, d: 20, h: 10, facade: "concrete", name: "Warehouse 1" },
    { x: 130, z: -55, w: 30, d: 20, h: 10, facade: "concrete", name: "Warehouse 2" },
    { x: 130, z: -80, w: 30, d: 20, h: 12, facade: "concrete", name: "Warehouse 3" },
    // Plaza-facing
    { x: 15, z: 18, w: 8, d: 6, h: 8, facade: "stone", name: "Plaza Cafe" },
    { x: -10, z: 18, w: 8, d: 6, h: 8, facade: "brick", name: "Plaza Bakery" },
    { x: 15, z: -18, w: 8, d: 6, h: 8, facade: "stone", name: "Plaza Florist" },
    { x: -10, z: -18, w: 8, d: 6, h: 8, facade: "wood", name: "Plaza Bookshop" },
  ];
  for (const spec of buildingSpecs) {
    objects.push(...building({
      name: spec.name,
      cx: spec.x, cz: spec.z,
      w: spec.w, d: spec.d, h: spec.h,
      facade: spec.facade,
      layer: LAYERS.buildings,
    }));
  }

  /* ---- park (lawn + trees) ---- */
  objects.push(prim({
    name: "Park lawn",
    pos: [-50, 0.03, 70],
    size: [60, 0.05, 60],
    color: C.grass,
    textureUrl: TEX_GRASS,
    textureRepeat: [15, 15],
    layer: LAYERS.park,
  }));
  for (let i = 0; i < 14; i++) {
    const tx = -75 + (i % 5) * 12 + ((i % 2) * 3);
    const tz = 50 + Math.floor(i / 5) * 18;
    // trunk
    objects.push(prim({
      name: `Tree trunk ${i + 1}`,
      pos: [tx, 1.5, tz],
      size: [0.5, 3, 0.5],
      shape: "cylinder",
      color: C.wood,
      textureUrl: TEX_WOOD,
      textureRepeat: [1, 1],
      layer: LAYERS.park,
    }));
    // canopy
    objects.push(prim({
      name: `Tree canopy ${i + 1}`,
      pos: [tx, 4.2, tz],
      size: [3, 3, 3],
      shape: "sphere",
      color: [0.25, 0.55, 0.22, 1],
      metalness: 0,
      roughness: 1,
      layer: LAYERS.park,
    }));
  }

  /* ---- train station ---- */
  // Long platform on the +Z axis, parallel to the rails (rails at x = -22).
  const PLAT_X = -18; // platform centre
  const PLAT_Z = 0;
  const PLAT_LEN = 60;
  objects.push(prim({
    name: "Station platform",
    pos: [PLAT_X, 0.5, PLAT_Z],
    size: [4, 1, PLAT_LEN],
    color: C.stone,
    textureUrl: TEX_STONE,
    textureRepeat: [2, 20],
    layer: LAYERS.station,
  }));
  // Columns
  for (let i = -2; i <= 2; i++) {
    objects.push(prim({
      name: `Station column ${i + 3}`,
      pos: [PLAT_X + 0.5, 3.5, i * 12],
      size: [0.6, 6, 0.6],
      shape: "cylinder",
      color: C.concrete,
      textureUrl: TEX_CONCRETE,
      textureRepeat: [1, 4],
      layer: LAYERS.station,
    }));
  }
  // Roof
  objects.push(prim({
    name: "Station roof",
    pos: [PLAT_X + 0.2, 7, PLAT_Z],
    size: [5.5, 0.4, PLAT_LEN + 2],
    color: C.metal,
    textureUrl: TEX_METAL,
    textureRepeat: [2, 20],
    metalness: 0.4,
    roughness: 0.4,
    layer: LAYERS.station,
  }));
  // Backwall (glass)
  objects.push(prim({
    name: "Station backwall",
    pos: [PLAT_X + 2.0, 3.5, PLAT_Z],
    size: [0.3, 6, PLAT_LEN],
    color: C.glass,
    textureUrl: TEX_GLASS_FACADE,
    textureRepeat: [12, 2],
    metalness: 0.4,
    roughness: 0.25,
    layer: LAYERS.station,
  }));
  // Benches
  for (let i = -2; i <= 2; i++) {
    objects.push(prim({
      name: `Bench ${i + 3}`,
      pos: [PLAT_X + 1.4, 1.3, i * 12 + 4],
      size: [1.5, 0.1, 0.5],
      color: C.wood,
      textureUrl: TEX_WOOD,
      textureRepeat: [2, 1],
      layer: LAYERS.station,
    }));
    objects.push(prim({
      name: `Bench legs ${i + 3}`,
      pos: [PLAT_X + 1.4, 0.85, i * 12 + 4],
      size: [1.5, 0.85, 0.08],
      color: C.metal,
      textureUrl: TEX_METAL,
      textureRepeat: [2, 1],
      layer: LAYERS.station,
    }));
  }
  // Sign
  objects.push(prim({
    name: "EASTLIGHT STATION sign",
    pos: [PLAT_X + 0.5, 7.6, 0],
    size: [10, 0.8, 0.2],
    color: C.white,
    metalness: 0.1,
    roughness: 0.3,
    layer: LAYERS.station,
  }));

  /* ---- rails ---- */
  // Two parallel rails along the straight section in front of the station.
  // (Decorative — the train follows the ScenePath, not the rail meshes.)
  for (const dx of [-22.6, -21.4]) {
    objects.push(prim({
      name: `Rail @x=${dx}`,
      pos: [dx, 0.12, 0],
      size: [0.12, 0.2, PLAT_LEN + 6],
      color: C.metal,
      metalness: 0.7,
      roughness: 0.3,
      textureUrl: TEX_METAL,
      textureRepeat: [1, 30],
      layer: LAYERS.station,
    }));
  }
  // Sleepers
  for (let z = -32; z <= 32; z += 2) {
    objects.push(prim({
      name: `Sleeper ${z}`,
      pos: [-22, 0.06, z],
      size: [2.4, 0.12, 0.4],
      color: C.wood,
      textureUrl: TEX_WOOD,
      textureRepeat: [1, 1],
      layer: LAYERS.station,
    }));
  }

  /* ---- train ---- */
  // The locomotive + 2 cars are simple primitive groups. The TrainRuntime
  // moves them along `path_train_track` and slides the door panels open.
  const locoId = newId("train_loco");
  const car1Id = newId("train_car");
  const car2Id = newId("train_car");
  const cabinId = newId("train_cabin");
  const door1L = newId("train_door");
  const door1R = newId("train_door");
  const door2L = newId("train_door");
  const door2R = newId("train_door");

  // Locomotive body — placed at the stop pose. Rails are at x=-22 (along Z).
  // The locomotive sits at the FRONT of the train; cars trail to -Z.
  // (At Play time the TrainRuntime overwrites positions anyway, but a
  // visually-correct edit pose helps when scrubbing in the editor.)
  const TRAIN_Y = 1.4;
  objects.push(prim({
    id: locoId,
    name: "Locomotive",
    pos: [-22, TRAIN_Y, 0],
    size: [2.4, 2.2, 7],
    color: C.trainRed,
    textureUrl: TEX_METAL,
    textureRepeat: [2, 6],
    metalness: 0.5,
    roughness: 0.4,
    layer: LAYERS.train,
    trainRole: "locomotive",
  }));
  // Locomotive cabin (the possess-this-to-drive trigger)
  objects.push(prim({
    id: cabinId,
    name: "Locomotive cabin",
    pos: [-22, TRAIN_Y + 1.6, 2.5],
    size: [2.6, 1.4, 2.2],
    color: C.trainRed,
    textureUrl: TEX_GLASS_FACADE,
    textureRepeat: [2, 2],
    metalness: 0.4,
    roughness: 0.25,
    layer: LAYERS.train,
    trainRole: "cabin",
  }));
  // Chimney (front of loco, ahead in +Z)
  objects.push(prim({
    name: "Locomotive chimney",
    pos: [-22, TRAIN_Y + 1.8, -2.5],
    size: [0.7, 1.4, 0.7],
    shape: "cylinder",
    color: C.black,
    metalness: 0.6,
    roughness: 0.3,
    layer: LAYERS.train,
  }));

  // Cars (passenger wagons). Each is a box with two sliding doors on the
  // +X (platform-facing) side.
  function buildCar(carId: string, posZ: number, label: string, doorL: string, doorR: string) {
    objects.push(prim({
      id: carId,
      name: label,
      pos: [-22, TRAIN_Y, posZ],
      size: [2.4, 2.2, 8],
      color: C.trainGold,
      textureUrl: TEX_METAL,
      textureRepeat: [2, 6],
      metalness: 0.5,
      roughness: 0.4,
      layer: LAYERS.train,
      trainRole: "car",
    }));
    // Door panels (left/right pair, sliding apart along local Z by 0.8m each)
    objects.push(prim({
      id: doorL,
      name: `${label} door L`,
      pos: [-20.85, TRAIN_Y, posZ - 0.85],
      size: [0.1, 1.8, 1.6],
      color: C.glass,
      textureUrl: TEX_GLASS_FACADE,
      textureRepeat: [1, 2],
      metalness: 0.5,
      roughness: 0.25,
      layer: LAYERS.train,
      trainRole: "door",
      doorOpenOffset: [0, 0, -1.4],
    }));
    objects.push(prim({
      id: doorR,
      name: `${label} door R`,
      pos: [-20.85, TRAIN_Y, posZ + 0.85],
      size: [0.1, 1.8, 1.6],
      color: C.glass,
      textureUrl: TEX_GLASS_FACADE,
      textureRepeat: [1, 2],
      metalness: 0.5,
      roughness: 0.25,
      layer: LAYERS.train,
      trainRole: "door",
      doorOpenOffset: [0, 0, 1.4],
    }));
    // Windows strip (decorative)
    objects.push(prim({
      name: `${label} windows`,
      pos: [-20.9, TRAIN_Y + 0.4, posZ],
      size: [0.05, 0.8, 7.2],
      color: C.glass,
      metalness: 0.5,
      roughness: 0.2,
      layer: LAYERS.train,
    }));
  }
  buildCar(car1Id, -10, "Car A", door1L, door1R);
  buildCar(car2Id, -19, "Car B", door2L, door2R);

  /* ---- animated decorations (rotating station sign) ---- */
  const spinId = newId("obj_spin");
  objects.push(prim({
    id: spinId,
    name: "Plaza pylon",
    pos: [0, 6, 0],
    size: [1.2, 12, 1.2],
    color: C.trainGold,
    metalness: 0.6,
    roughness: 0.3,
    layer: LAYERS.roads,
  }));
  // Slow spin on Y over 8 seconds
  animations.push({
    id: newId("anim"),
    name: "Plaza pylon spin",
    targetId: spinId,
    loop: true,
    duration: 8,
    keyframes: [
      { t: 0, rotation: [0, 0, 0] },
      { t: 8, rotation: [0, Math.PI * 2, 0] },
    ] as AnimationKeyframe[],
  });

  /* ---- characters ---- */
  // Playable spawn on the plaza
  const playable: CharacterObject = {
    id: newId("chr"),
    name: "You",
    kind: "character",
    url: DEFAULT_CHARACTER_URL,
    source: "Xbot (Mixamo)",
    position: [0, 0.1, 5],
    rotation: [0, Math.PI, 0],
    scale: [1, 1, 1],
    visible: true,
    layerId: LAYERS.characters,
    animationSpeed: 1,
    paused: false,
    crossfade: 0.2,
    playable: true,
    controlScheme: "both",
    cameraMode: "third",
    locomotion: {
      walkSpeed: 2.2,
      runSpeed: 5.5,
      jumpHeight: 1.4,
      gravity: 22,
      height: 1.7,
      radius: 0.32,
      maxStepHeight: 0.45,
    },
  };
  objects.push(playable);

  // NPC commuters on the platform
  for (let i = 0; i < 4; i++) {
    const npc: CharacterObject = {
      id: newId("chr"),
      name: `Commuter ${i + 1}`,
      kind: "character",
      url: DEFAULT_CHARACTER_URL,
      source: "Xbot (Mixamo)",
      position: [PLAT_X + 0.5, 1.0, -16 + i * 8],
      rotation: [0, -Math.PI / 2, 0],
      scale: [1, 1, 1],
      visible: true,
      layerId: LAYERS.characters,
      animationSpeed: 1,
      paused: false,
      crossfade: 0.2,
      currentAnimation: ["idle", "idle", "wave", "dance"][i],
    };
    objects.push(npc);
  }

  /* ---- terrain (sculpted hills) ---- */
  const terrain = defaultTerrain();
  terrain.enabled = true;
  terrain.size = [400, 1, 400];
  terrain.color = [0.22, 0.4, 0.18, 1];
  terrain.snapToSurface = false;
  terrain.texture = { url: TEX_GRASS, name: "Grass", repeat: 80 };
  terrain.material = {
    metalness: 0,
    roughness: 1,
    reflectivity: 0.2,
    preset: "custom",
  };
  const RES = 96;
  terrain.heightmap = { resolution: RES, data: buildHeightmap(RES, 400) };

  /* ---- lights ---- */
  const lights: SceneLight[] = [
    {
      id: "ml-sun",
      name: "Sun",
      kind: "directional",
      position: [80, 120, 40],
      color: [1, 0.97, 0.88, 1],
      intensity: 1.5,
      castShadow: true,
    },
    {
      id: "ml-amb",
      name: "Ambient",
      kind: "ambient",
      position: [0, 0, 0],
      color: [0.6, 0.75, 0.95, 1],
      intensity: 0.35,
    },
    {
      id: "ml-plat",
      name: "Platform spot",
      kind: "spot",
      position: [PLAT_X + 0.2, 6.5, 0],
      target: [PLAT_X, 1, 0],
      color: [1, 0.92, 0.78, 1],
      intensity: 1.2,
      castShadow: false,
    },
  ];

  /* ---- train system config ---- */
  // The stops sit at the t-values where the path passes through the
  // station-straight middle. Our buildTrack() emits 3 points in the
  // straight (indexes 0..2). The platform-centre point is index 2 (Z=0).
  // We don't know the exact t until the runtime measures arc length, so
  // we store a stop position as the WORLD position of the platform stop
  // anchor — but the simpler way is to pick a t-fraction by ratio. With
  // 24 control points, station centre is point #2 → t≈2/24=0.083.
  const trainSystem: TrainSystemConfig = {
    trackPathId: "path_train_track",
    locomotiveId: locoId,
    carIds: [car1Id, car2Id],
    doorIds: [door1L, door1R, door2L, door2R],
    cabinId,
    stops: [{ t: 0.085, name: "Eastlight Station" }],
    baseSpeed: 9, // m/s cruise
    brakeDistance: 24, // m
    stopDurationSeconds: 10,
    doorAnimSeconds: 1.4,
    carSpacing: 8.5,
    possessKey: "P",
  };

  return {
    ...EMPTY_SCENE,
    layers: makeLayers(),
    terrain,
    objects,
    animations,
    scenePaths: [buildTrack()],
    lights,
    trainSystem,
    environment: {
      background: "#86a8c6",
      ambient: 0.45,
      fog: { color: "#9bbed8", near: 120, far: 380 },
      gi: {
        enabled: true,
        skyColor: "#cfe6ff",
        groundColor: "#3d5c3d",
        hemisphereIntensity: 0.55,
        contactShadows: true,
        contactOpacity: 0.35,
        contactBlur: 2.5,
      },
    },
  };
}

/** Public preset metadata used by the Level Wizard gallery. */
export const MASTER_LEVEL_PRESET = {
  id: "master_eastlight_town",
  name: "Eastlight Town",
  blurb: "A 400×400 m district with sculpted hills, ~30 textured buildings, a glass-and-stone station, and a 3-car train you can board.",
  size: "town" as const,
  build: buildMasterLevelScene,
};